### ISSUE TITLE
AC Training Claimed HTTPS reference

### ISSUE THREAD

**Issue by dallastjames** [ionic-enterprise/ionic-training-decks#58]
In the new Auth Connect training, it would be good to include some verbiage related to Claimed HTTPS urls and how you can use those instead of the custom auth protocol. Certain providers may only accept HTTPS urls and not custom protocols which makes this an important point for some people. Additionally, claimed HTTPS *ensure* that your domain is unique to your app, whereas custom auth protocols, while simpler, is always at risk of having a conflict with another app installed onto another user's application. 

We have documentation for setting this up that we can link to here: https://capacitorjs.com/docs/v3/guides/deep-links#creating-site-association-files

**Comment by kensodemann** [comment]
This has long since changed and we will add a tutorial for it instead.
